GET http://localhost:8000

###

POST http://localhost:8000/add
Content-Type:  application/json

{
    "item": "Third Item",
    "status": false
}

###
DELETE http://localhost:8000/5ef860a90057dc7d009eadff

###
PUT http://localhost:8000/5ef860b900c4bd40009eae00
Content-Type:  application/json

{
    "item": "New Item",
    "status": false
}
