POST http://localhost:8000
Content-Type: application/json

{
    "item" : "todo",
    "status":false
}


###
GET http://app-52321a87-f8a8-4868-b4c8-aa737d4db5f9.cleverapps.io/


###
DELETE  http://localhost:8000/5ef6318b009bcdb900f8cf0e

###

PUT   http://localhost:8000/5ef6319100a6bcf000f8cf0f
Content-Type: application/json

{
    "item":"Updated",
    "status": true
}